/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CertificationRouteImport } from './routes/certification'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as WhyInvestmentBankingRouteImport } from './routes/why-investment-banking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationRoute = CertificationRouteImport.update({
  id: '/certification',
  path: '/certification',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyInvestmentBankingRoute = WhyInvestmentBankingRouteImport.update({
  id: '/why-investment-banking',
  path: '/why-investment-banking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certification': typeof CertificationRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/skills': typeof SkillsRoute
  '/why-investment-banking': typeof WhyInvestmentBankingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certification': typeof CertificationRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/skills': typeof SkillsRoute
  '/why-investment-banking': typeof WhyInvestmentBankingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certification': typeof CertificationRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/skills': typeof SkillsRoute
  '/why-investment-banking': typeof WhyInvestmentBankingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/certification'
    | '/contact'
    | '/experience'
    | '/skills'
    | '/why-investment-banking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/certification'
    | '/contact'
    | '/experience'
    | '/skills'
    | '/why-investment-banking'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/certification'
    | '/contact'
    | '/experience'
    | '/skills'
    | '/why-investment-banking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CertificationRoute: typeof CertificationRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRoute
  SkillsRoute: typeof SkillsRoute
  WhyInvestmentBankingRoute: typeof WhyInvestmentBankingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification': {
      id: '/certification'
      path: '/certification'
      fullPath: '/certification'
      preLoaderRoute: typeof CertificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-investment-banking': {
      id: '/why-investment-banking'
      path: '/why-investment-banking'
      fullPath: '/why-investment-banking'
      preLoaderRoute: typeof WhyInvestmentBankingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CertificationRoute: CertificationRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRoute,
  SkillsRoute: SkillsRoute,
  WhyInvestmentBankingRoute: WhyInvestmentBankingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
